config/routes.rb
Wedding::Application.routes.draw do
  
  get "users/new/:object" => "users#new", as: :new_user
  get "users/:id/edit/:object" => "users#edit", as: :edit_user 
  resources :users, except: [:new, :edit] do
    collection do
      get :authentification
      post :authenticate
    end
  end

  resources :songs

  resources :welcomes, only: [:index]
  
  namespace :admin do
    resources :users, only: [] do
      collection do
        get :responses
        get :addresses
        get :messages
      end
    end
    root 'users#responses'
  end

  root 'welcomes#index'

end

app/models/user.rb
# coding: utf-8
# 
# == Schema Information
#
# Table name: users
#
#  id                 :integer          not null, primary key
#  firstname          :string(255)
#  lastname           :string(255)
#  email              :string(255)
#  login              :string(255)
#  salt               :string(255)
#  encrypted_password :string(255)
#  partner_id         :integer
#  street             :string(255)
#  address_add        :string(255)
#  town               :string(255)
#  zip_code           :string(255)
#  message_address    :text
#  created_at         :datetime
#  updated_at         :datetime
#  presence           :string(255)
#  message_response   :string(255)
#  phone              :string(255)
#

require 'bcrypt'
require 'yaml'
require 'csv'

class String
  def without_accent
    gsub(/[ÀÁÂÃÄáàâäã]/, "a").gsub(/[Çç]/, "c").gsub(/[ÈÉÊËẼéèêëẽ]/, "e").gsub(/[ÌÍÎÏĨîïíĩì]/, "i").gsub(/[ÒÓÔÕÖôöóòõ]/, "i").gsub(/[ÙÚÛÜŨùúûüũ]/, "i").titleize
  end
end

class User < ActiveRecord::Base
	before_validation :cypher_password, if: :password
	before_validation :set_login
  before_save :set_response
	after_save :save_partner

	validates_uniqueness_of :login
	validates_presence_of :login

	def password=(password); @password = password; end
	def password; @password; end

	def name; "#{self[:firstname]} #{self[:lastname]}"; end

	def wedding=(value); response[:wedding] = value; end
	def cocktail=(value); response[:cocktail] = value; end
	def dinner=(value); response[:dinner] = value; end
	def party=(value); response[:party] = value; end
	def wedding; response[:wedding]; end
	def cocktail; response[:cocktail]; end
	def dinner; response[:dinner]; end
	def party; response[:party]; end
	def set_response; self.presence = self.response.to_yaml; end
	def response; @response ||= (self.presence ? YAML.load(presence) : {}); end
  def response?; response.present?; end
  def comes?; presence =~ /1/; end

	def partner; @partner ||= User.new; end
	def partner=(partner); @partner = partner; end
	def save_partner
		if partner[:firstname].present?
			self.class.where(login: self.class.login( partner)).first_or_create!.update_attributes!(partner)
		end
		true
  rescue
    true
	end

	def set_login;	self[:login] ||= User.login(self);	end
	def self.login(user_hash); puts user_hash[:firstname]; "#{user_hash[:firstname]}#{user_hash[:lastname]}".without_accent.gsub(/\s+/, "");		end

	def self.create_admin_user(password)
		User.where(firstname: "admin", lastname: "admin", login: "admin").first_or_create!.update_attributes!(password: password)
	end
	def self.admin_user
    	find_by!(firstname: "admin", lastname: "admin", login: "admin")
	end
	def self.create_default_user(password)
		User.where(firstname: "default", lastname: "user", login: "default user").first_or_create!.update_attributes!(password: password)
	end
	def self.default_user
    	find_by!(firstname: "default", lastname: "user", login: "default user")
	end
	  
	def self.name_without_accent(hash)
		{firstname: hash[:firstname], lastname: hash[:lastname].without_accent}
	end

	def cypher_password
		self[:salt] = BCrypt::Engine.generate_salt
		self[:encrypted_password] = BCrypt::Engine.hash_secret(@password, self[:salt])
	end

	def self.check_admin_password(password)
		BCrypt::Engine.hash_secret(password, admin_user[:salt]) == admin_user[:encrypted_password]
	end
	def self.check_default_password(password)
		BCrypt::Engine.hash_secret(password, default_user[:salt]) == default_user[:encrypted_password]
	end
  
  
  ##### EXPORT CSV
  
  ADDRESS_HEADER = ["Nom", "Prénom", "Rue", "Complément", "Ville", "Code postal", "Adresse internet", "Téléphone", "Nom", "Prénom", "Message"]
  RESPONSE_HEADER = ["Nom", "Prénom", "Cérémonie", "Cocktail", "Dinner", "Soirée", "Nom", "Prénom", "Cérémonie", "Cocktail", "Dinner", "Soirée", "Message"]
  
  def self.users_with_address; User.where("town IS NOT NULL").all; end
  def self.addresses
    CSV.generate( col_sep: ";") do |csv|
      csv << ADDRESS_HEADER
      User.users_with_address.each{ |user| csv << [user[:lastname], user[:firstname], user[:street], user[:address_add], user[:town], user[:zip_code], user[:email], user[:phone], user.partner.try(:lastname), user.partner.try(:firstname), user[:message_address],]} #
    end
  end
  def self.users_with_response; User.where("presence != '--- {}\n'").all; end
  def self.responses
    CSV.generate( col_sep: ";") do |csv|
      csv << RESPONSE_HEADER
      User.users_with_response.each{ |user| csv << [user[:lastname], user[:firstname], user.wedding, user.cocktail, user.dinner, user.party, user.partner.try(:lastname), user.partner.try(:firstname), user.partner.try(:wedding), user.partner.try(:cocktail), user.partner.try(:dinner), user.partner.try(:party), user[:message_response],]} #
    end
  end
  
end

app/controllers/admin/users_controller.rb
# coding: utf-8
# 

class Admin::UsersController < ApplicationController
  
  before_action :authenticated_filter
  
  def addresses
    do_and_respond(:addresses) do
      if csv_request?
        @csv = User.addresses
        @filename = "adresses.csv"
      else
        @users = User.users_with_address
      end
    end
  end
  def responses
    do_and_respond(:responses) do
      if csv_request?
        @csv = User.responses
        @filename = "responses.csv"
      else
        @users = User.users_with_response
      end
    end
  end
  def messages
    do_and_respond(:messages) do
      @users = User.all
    end
  end

private
  def user_params
    params.require(:user).except!(:login, :password, :encrypted_password).permit!
  end
end

app/controllers/users_controller.rb
# coding: utf-8
# 

class UsersController < ApplicationController

  def index
    do_and_respond(:index) do
    end
  end

  def show
    do_and_respond(:show) do
    end
  end

  def new
    puts ["new", params, @current_user.try(:name)]
    return edit if @current_user
    do_and_respond(:new) do
      @current_user = User.new
      @object = params[:object]
    end
  end
  
  def edit
    puts ["edit", params, @current_user.try(:name)]
    do_and_respond(:edit, :show) do
      @object = params[:object]
    end
  end
  
  def create
    puts ["create", params, @current_user.try(:name)]
    update
  end
  
  def update
    puts ["update", params, @current_user.try(:name)]
    do_and_respond(:redirect_to_welcomes_path) do
      @current_user = User.where(login: User.login(user_params)).first_or_create!
      @current_user.update_attributes!(user_params)
    end
  end
  
  def authentification
    do_and_respond(:authentification, :index) do
    end
  end
  
  def authenticate
    puts params[:password]
    do_and_respond(:redirect_to_responses_admin_users_path, :authentification) do
      @authenticated = "authentification de premier niveau" if User.check_admin_password(params[:password])
      raise "Utilisateur non authentifié" if @authenticated != "authentification de premier niveau"
    end
  end

private
  def user_params
    params.require(:user).except!(:login, :password, :encrypted_password).permit!
  end
end

app/views/users/_address.html.erb
<h1 class="text-center">1 adresse = 1 faire part<small>... ou plus si affinité !</small></h1>
<br />
<div class="row main_grey"><br />
  <div class=" col-xs-12 col-sm-12 col-md-10 col-lg-8 col-md-offset-1 col-lg-offset-2">
    <div class="row">
    <%= form_for @current_user do |f| %>
    	<div class="user_name">
    		<div id="firstname" class="form-group col-xs-12 col-sm-6 col-md-6 col-lg-6"><%= f.label "Prénom" %><br /><%= f.text_field :firstname, placeholder: "Emmanuel", class: "form-control", required: "required" %></div>
    		<div id="lastname" class="form-group col-xs-12 col-sm-6 col-md-6 col-lg-6"><%= f.label "Nom_de_famille" %><br /><%= f.text_field :lastname, placeholder: "Delmas", class: "form-control", required: "required" %></div>
    	</div>
    	<div class="user_email_phone">
    		<div id="email" class="form-group col-xs-12 col-sm-6 col-md-6 col-lg-6"><%= f.label "Courriel" %><br />
    			<div class="input-group">
    				<span class="input-group-addon">@</span><%= f.email_field :email, class: "form-control" %>
    			</div>
    		</div>
    		<div id="phone" class="form-group col-xs-12 col-sm-6 col-md-6 col-lg-6"><%= f.label "Téléphone" %><br /><%= f.telephone_field :phone, class: "form-control" %></div>
    	</div>
    	<div class="user_address">
    			<div id="street" class="form-group col-xs-12 col-sm-12 col-md-12 col-lg-12"><%= f.label "Numéro_et_voie" %><br /><%= f.text_field :street, placeholder: "5 rue Clodion", class: "form-control", required: "required" %></div>
    			<div id="zip_code" class="form-group col-xs-12 col-sm-6 col-md-6 col-lg-6"><%= f.label "Code_postal" %><br /><%= f.text_field :zip_code, placeholder: "75015", class: "form-control", required: "required" %></div>
    			<div id="town" class="form-group col-xs-12 col-sm-6 col-md-6 col-lg-6"><%= f.label "Ville" %><br /><%= f.text_field :town, placeholder: "Paris", class: "form-control", required: "required" %></div>
    		</div>
    		<div class="checkbox col-xs-12 col-sm-12 col-md-12 col-lg-12">
    			<label class="address_check_box"><%= check_box_tag :address_check_box, required: "required" %><%= label_tag "Je reconnais les informations ci-dessus comme exacte, et assure être domicilié à cette même adresse jusqu'en septembre 2014." %></label>
    		</div>
    	<div class="user_message col-xs-12 col-sm-12 col-md-12 col-lg-12">
    		<div class="" id="message_addres"><%= f.label "Message" %><br /><%= f.text_area :message_address, placeholder: "Je suis trop heureuse pour vous ! C'est génial ce que vous faites.", class: "form-control", rows: "3" %></div>
    	</div>
    	<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
    		<br />
    		<div class="submit_form" id="submit_address"><%= f.submit "Soumettre", class: "btn btn-primary" %></div>
    	</div>
    <% end %>
    </div>
  </div>
</div>

app/views/users/_password.html.erb
<%= form_tag(authenticate_users_path, method: "post") do %>
	<%= password_field_tag(:password) %>
<% end %>

app/views/users/_response.html.erb
<h1 class="text-center">Yes we come !</h1>
<br />
<div class="row main_grey"><br />
  <div class=" col-xs-12 col-sm-12 col-md-10 col-lg-8 col-md-offset-1 col-lg-offset-2">
    <div class="row">
      <div class="row main_grey">
      <%= form_for @current_user, role: "form" do |f| %>
      	<div class="you col-xs-12 col-sm-6 col-md-6 col-lg-6">
      		<h3>Vous</h3>
      		<div class="user_name">
      			<div class="form-group" id="firstname"><%= f.label "Prénom", for: "user_firstname" %><br /><%= f.text_field :firstname, placeholder: "Emmanuel", class: "form-control", required: "required" %></div>
      			<div class="form-group" id="lastname"><%= f.label "Nom", for: "user_lastname" %><br /><%= f.text_field :lastname, placeholder: "Delmas", class: "form-control", required: "required" %></div>
      			<div class="form-group" id="email">
      				<%= f.label "Courriel", for: "user_email" %><br />
      				<div class="input-group">
                <span class="input-group-addon">@</span><%= f.email_field :email, class: "form-control" %>
              </div>
            </div>
      		</div>
      		<h3>Je viendrai...</h3>
      		<div class="user_response row">
      			<div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
      				<div class="row" id="wedding">
      						<div class="col-xs-1 col-sm-1 col-md-1 col-lg-1"><%= f.check_box :wedding, class: "pull-left" %></div>
      						<div class="col-xs-10 col-sm-10 col-md-10 col-lg-10"><%= f.label "à la cérémonie", class: "pull-left" %></div>
      				</div>
      				<div class="row" id="cocktail">
      						<div class="col-xs-1 col-sm-1 col-md-1 col-lg-1"><%= f.check_box :cocktail, class: "pull-left" %></div>
      						<div class="col-xs-10 col-sm-10 col-md-10 col-lg-10"><%= f.label " au cocktail (sur invitation)", class: "pull-left" %></div>
      				</div>
      			</div>
      			<div class="col-xs-6 col-sm-6 col-md-6 col-lg-6 pull-left">
      				<div class="row" id="dinner">
      						<div class="col-xs-1 col-sm-1 col-md-1 col-lg-1"><%= f.check_box :dinner, class: "pull-left" %></div>
      						<div class="col-xs-10 col-sm-10 col-md-10 col-lg-10"><%= f.label " au dîner (sur invitation)", class: "pull-left" %></div>
      				</div>
      				<div class="row" id="party">
      						<div class="col-xs-1 col-sm-1 col-md-1 col-lg-1"><%= f.check_box :party, class: "pull-left" %></div>
      						<div class="col-xs-10 col-sm-10 col-md-10 col-lg-10"><%= f.label "à la soirée (sur invitation)", class: "pull-left" %></div>
      				</div>
      			</div>
      		</div>
      	</div>
      	<div class="partner col-xs-12 col-sm-6 col-md-6 col-lg-6">
      	<h3>Votre conjoint</h3>
      	<%= f.fields_for :partner do |p| %>
      		<div class="user_name">
      			<div class="form-group" id="firstname"><%= p.label "Prénom" %><br /><%= p.text_field :firstname, placeholder: "Marie-Liesse", value: @current_user.partner.firstname, class: "form-control" %></div>
      			<div class="form-group" id="lastname"><%= p.label "Nom_de_famille" %><br /><%= p.text_field :lastname, placeholder: "Clement", value: @current_user.partner.lastname, class: "form-control" %></div>
      			<div class="form-group" id="email">
      				<%= p.label "Courriel" %><br />
      				<div class="input-group">
      					<span class="input-group-addon">@</span><%= p.email_field :email, value: @current_user.partner.email, class: "form-control" %>
      				</div>
      			</div>
      		</div>
      		<h3>Je viendrai...</h3>
      		<div class="user_response row">
      			<div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
      				<div class="row" id="wedding">
      					<div class="col-xs-1 col-sm-1 col-md-1 col-lg-1"><%= p.check_box :wedding, value: @current_user.partner.wedding, class: "pull-left" %></div>
      					<div class="col-xs-10 col-sm-10 col-md-10 col-lg-10"><%= p.label "à la cérémonie", class: "pull-left" %></div>
      				</div>
      				<div class="row" id="cocktail">
      					<div class="col-xs-1 col-sm-1 col-md-1 col-lg-1"><%= p.check_box :cocktail, value: @current_user.partner.cocktail, class: "pull-left" %></div>
      					<div class="col-xs-10 col-sm-10 col-md-10 col-lg-10"><%= p.label " au cocktail (sur invitation)", class: "pull-left" %></div>
      				</div>
      			</div>
      			<div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
      				<div class="row" id="dinner">
      					<div class="col-xs-1 col-sm-1 col-md-1 col-lg-1"><%= p.check_box :dinner, value: @current_user.partner.dinner, class: "pull-left" %></div>
      					<div class="col-xs-10 col-sm-10 col-md-10 col-lg-10"><%= p.label " au dîner (sur invitation)", class: "pull-left" %></div>
      				</div>
      				<div class="row" id="party">
      					<div class="col-xs-1 col-sm-1 col-md-1 col-lg-1"><%= p.check_box :party, value: @current_user.partner.party, class: "pull-left" %></div>
      					<div class="col-xs-10 col-sm-10 col-md-10 col-lg-10"><%= p.label "à la soirée (sur invitation)", class: "pull-left" %></div>
      				</div>
      			</div>
      		</div>
      	</div>
      	<% end %>
      	<div class="user_message col-xs-12 col-sm-12 col-md-12 col-lg-12">
      		<br />
      		<h3>Un petit mot ?</h3>
      		<div class="" id="message_response"><%= f.text_area :message_response, placeholder: "Trop pressé d'être le jour J. On va s'éclater. Je vous kiff trop !", class: "form-control", required: "required", rows: "3" %></div>
      	</div>
      	<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
      		<br />
      		<div class="submit_form" id="submit_address"><%= f.submit "Soumettre", class: "btn btn-primary" %></div>
      	</div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/authentification.html.erb
<%= render partial: "password" %>

app/views/users/edit.html.erb
<%= render partial: @object %>

app/views/users/index.html.erb
<%= render partial: "password" %>

app/views/users/new.html.erb
<%= render partial: @object %>

app/views/users/show.html.erb
<p>This is you !</p>