config/routes.rb
Wedding::Application.routes.draw do
  
  get "users/new/:object" => "users#new", as: :new_user
  get "users/:id/edit/:object" => "users#edit", as: :edit_user 
  resources :users, except: [:new, :edit] do
    collection do
      get :authentification
      post :authenticate
    end
  end

  resources :songs

  resources :welcomes, only: [:index]
  
  namespace :admin do
    resources :users, only: [] do
      collection do
        get :responses
        get :addresses
        get :messages
      end
    end
    root 'users#responses'
  end

  root 'welcomes#index'

end

app/models/song.rb
# coding: utf-8

class Song
	attr_reader :id, :name, :title, :type, :author
  
	def initialize(id, name, title, type, author)
		@id = id
		@name = name
		@title = title
		@type = type
		@author = author
	end

  SONGS = [
    Song.new(0, "sarabande", "Sarabande, marche Nuptial", "Procession", "Heandel"),
    Song.new(1, "psaumme_118", "Psaume 118", "Louange d'entrée", ""),
    Song.new(2, "kyrie", "Messe de l'Emmanuel", "Kyrie", "Communauté de l'Emmanuel"),
    Song.new(3, "gloria", "Messe de l'Emmanuel", "Gloria", "Communauté de l'Emmanuel"),
    Song.new(4, "psaume", "Le Seigneur est ma Lumière et mon Salut", "Psaume", ""),
    Song.new(5, "alleluia", "Messe de l'Emmanuel", "Alleluia", "Communauté de l'Emmanuel"),
    Song.new(6, "litanie", "Litanie des saints Congolaise", "Litanie des saints", "Communauté du Chemin Neuf"),
    Song.new(7, "veni_sancte_spiritus", "Veni Sancte Spiritus", "Invocation à l'Esprit", "Anuncio"),
    Song.new(8, "acclamez_dieu_toute_la_terre", "Acclamez Dieu toute la Terre", "Action de grâce", "Communauté de l'Emmanuel"),
    Song.new(9, "chant_promesse", "Chant de la promesse", "Promesse scout", "Père Jacques Sevin"),
    Song.new(10, "mendiez", "Mendiez l'humilité", "Prière universelle", "Frère Jean-Baptiste"),
    Song.new(11, "ne_crains_pas", "Ne crains pas, Je suis ton Dieu", "Offertoire", "Frère Jean-Baptiste"),
    Song.new(12, "sanctus", "Messe de l'Emmanuel", "Sanctus", "Communauté de l'Emmanuel"),
    Song.new(13, "anamnese", "Messe de l'Emmanuel", "Anamnèse", "Communauté de l'Emmanuel"),
    Song.new(14, "agnus", "Messe de l'Emmanuel", "Agnus", "Communauté de l'Emmanuel"),
    Song.new(15, "tu_fais_ta_demeure_en_nous", "Tu fais ta demeure en nous", "Communion", "Communauté de l'Emmanuel"),
    Song.new(16, "humblement_dans_le_silence", "Humblement dans le silence", "Méditation", "Frère Jean-Baptiste"),
    Song.new(17, "regarde_letoile", "Regarde l'étoile", "Invocation mariale", "Communauté de l'Emmanuel"),
    Song.new(18, "jubilez", "Jubilez", "Louange finale", "Frère Jean-Baptiste"),
  ].freeze

  def self.all;  	SONGS.compact;  end
  def self.find(id);  	SONGS[id];  end

  def self.welcome_song;    find(18);  end

  def filename;  @title =~ /Messe de l'Emmanuel/ ? "messe_emmanuel.pdf" : "#{@name}.pdf";  end

end

app/controllers/songs_controller.rb
# coding: utf-8

class SongsController < ApplicationController
	def index
		do_and_respond do
      if zip_request?
        @send_file = true
        @filename = "partitions.zip"
        @file_path = "#{Rails.root}/public/partitions/#{@filename}"
      end
    end
	end
	def show
		do_and_respond(:show, :index) do
      @song = Song.find(params[:id].to_i)
      if pdf_request?
        @send_file = true
        @filename = @song.filename
        @file_path = "#{Rails.root}/public/partitions/#{@filename}"
      else
  		  @song = Song.find(params[:id].to_i)
      end
  	end
	end

protected
end

app/views/songs/_song.html.erb
<% content_for :script do %>
<script type="text/javascript">
  $(document).ready(function(){
    $("#jquery_jplayer_1").jPlayer({
      ready: function () {
        $(this).jPlayer("setMedia", {
          mp3: "/audios/<%= song.name %>.mp3",
          oga: "/audios/<%= song.name %>.ogg"
        });
      },
      swfPath: "/js",
      supplied: "mp3,oga"
    });
  });
</script>
<% end %>

<div id="jquery_jplayer_1" class="jp-jplayer"></div>
<div id="jp_container_1" class="jp-audio">
	<div class="jp-type-single">
	  <div class="jp-gui jp-interface">
	    <ul class="jp-controls">
	      <li><a href="javascript:;" class="jp-play" tabindex="1">play</a></li>
	      <li><a href="javascript:;" class="jp-pause" tabindex="1">pause</a></li>
	      <li><a href="javascript:;" class="jp-stop" tabindex="1">stop</a></li>
<!-- 	      <li><a href="javascript:;" class="jp-mute" tabindex="1" title="mute">mute</a></li>
	      <li><a href="javascript:;" class="jp-unmute" tabindex="1" title="unmute">unmute</a></li>
	      <li><a href="javascript:;" class="jp-volume-max" tabindex="1" title="max volume">max volume</a></li> -->
	    </ul>
	    <div class="jp-progress">
	      <div class="jp-seek-bar">
	        <div class="jp-play-bar"></div>
	      </div>
	    </div>
<!-- 	    <div class="jp-volume-bar">
	      <div class="jp-volume-bar-value"></div>
	    </div> -->
	    <div class="jp-time-holder">
	      <div class="jp-current-time"></div>
	      <div class="jp-duration"></div>
<!-- 	      <ul class="jp-toggles">
	        <li><a href="javascript:;" class="jp-repeat" tabindex="1" title="repeat">repeat</a></li>
	        <li><a href="javascript:;" class="jp-repeat-off" tabindex="1" title="repeat off">repeat off</a></li>
	      </ul> -->
	    </div>
	  </div>
	  <div class="jp-title">
	    <ul>
	      <li><%= song.title %></li>
	    </ul>
	  </div>
	  <div class="jp-no-solution">
	    <span>Update Required</span>
	    To play the media you will need to either update your browser to a recent version or update your
	    <a href="http://get.adobe.com/flashplayer/" target="_blank">Flash plugin</a>.
	  </div>
	</div>
</div>

app/views/songs/_words.html.erb
<p>
  <%= "#{song.title} - #{song.type} - #{song.author}" %><br />
  <br />
  <%= link_to "Obtenir la partition", song_path("#{song.id}.pdf"), target: "_blank" %><br />
</p>
<% case song.id %>
<% when 0 %>
<% when 1 %>
<p>
  Alléluia, Alléluia, Alléluia.<br />
  <br />
  Proclamez que le Seigneur est bon, Eternel est son amour,<br />
  Que le dise la maison d’Israël, Eternel est son amour.<br />
  <br />
  Le Seigneur est ma force et mon chant, Le Seigneur est mon salut,<br />
  Je ne mourrai pas, non, je vivrai, Je dirai l’œuvre de Dieu.<br />
  <br />
  Dans l’angoisse, j’ai crié vers lui, Le Seigneur m’a exaucé,<br />
  Le Seigneur est là pour me défendre, J’ai bravé mes ennemis.<br />
  <br />
  Ouvrez-moi les portes de justice, J’entrerai, je rendrai grâce,<br />
  C’est ici la porte du Seigneur, Tous les justes y entreront.<br />
  <br />
  Oui, c’est toi mon Dieu, je te rends grâce, Seigneur mon Dieu, je t’exalte,<br />
  Proclamez que le Seigneur est bon, Eternel est son amour.<br />
</p>
<% when 2 %>
<p>
  Seigneur Jésus envoyé par le père guérir et sauver les hommes.<br />
  Prends pitié de nous.<br />
  <br />
  Kyrie eleison, Kyrie eleison, Kyrie eleison.<br />
  <br />
  Au christ venu dans le monde appelé tous les pécheurs.<br />
  Prends pitié de nous.<br />
  <br />
  Christe eleison, Christe eleison, Christe eleison.<br />
  <br />
  Seigneur élevé dans la gloire du père ou tu intercèdes pour nous.<br />
  Prend pitié de nous<br />
  <br />
  Kyrie eleison, Kyrie eleison, Kyrie eleison.<br />
</p>
<% when 3 %>
<p>
  Gloria gloria in excelcis deo. Gloria gloria in excelcis deo.<br />
  <br />
  Et paix sur la Terre aux hommes qu'il aime. Nous te louons,<br />
  nous te bénissons, nous t'adorons, nous te glorifions,<br />
  nous te rendons grâce pour ton immense gloire.<br />
  Seigneur Dieu, Roi du Ciel, Dieu le Père tout puissant.<br />
  Seigneur Fils unique Jésus-Christ, Seigneur Dieu, Agneau de Dieu, le Fils du Père,<br />
  <br />
  Toi qui enlèves le péché du monde, prends pitié de nous,<br />
  Toi qui enlèves le péché du monde, reçois notre prière.<br />
  Toi qui es assis à la droite du Père, prends pitié de nous.<br />
  <br />
  Car Toi seul es Saint, toi seul es Seigneur, toi seul es le Très-Haut,<br />
  Jésus-Christ, avec le Saint Esprit, dans la gloire de Dieu le père. Amen.<br />
</p>
<% when 4 %>
<p>
  Refrain<br />
  Le Seigneur est ma lumière et mon salut,<br />
  De qui aurais-je crainte ?<br />
  Le Seigneur est le rempart de ma vie,<br />
  Devant qui tremblerais-je ?<br />
  <br />
  1/ J'ai demandé une chose au Seigneur,<br />
  La seule que je cherche :<br />
  Habiter la maison du Seigneur<br />
  tous les jours de ma vie.<br />
  <br />
  2/ Habiter ta maison, Seigneur,<br />
  Pour t'admirer en ta beauté<br />
  Et m'attacher à ton Eglise, Seigneur,<br />
  m'attacher à ton Eglise, Seigneur.<br />
  <br />
  3/ J'en suis sûr, je verrai la bonté du Seigneur<br />
  Sur la terre des vivants.<br />
  Espère, sois fort et prends courage,<br />
  Espère, espère le Seigneur !<br />
</p>
<% when 5 %>
<p>
  Alléluia, alléluia, alléluia, alléluia. Bis
</p>
<% when 6 %>
<% when 7 %>
<% when 8 %>
<a href="http://grooveshark.com/#!/search/song?q=Chants+de+l%27Emmanuel+Acclamez+Dieu%2C+toute+la+terre">Ecouter sur grooveshark</a>
<br />
<p>
  Acclamez Dieu toute la terre.<br />
  Servez-le dans l'allégresse.<br />
  Allez à Lui avec des chants de joie,<br />
  Car éternel est son amour.<br />
  <br />
  Refrain<br />
  Alléluia, alléluia, alléluia, alléluia.<br />
  <br />
  Allez à Lui en rendant grâce,<br />
  Dans ses parvis avec des hymnes,<br />
  Rendez-Lui grâce et bénissez son nom,<br />
  Car éternel est son amour.<br />
  <br />
  Lui, le Seigneur est notre Dieu,<br />
  Nous, le troupeau de son bercail,<br />
  Il nous a fait et nous sommes à Lui,<br />
  Car éternel est son amour.<br />
</p>
<% when 9 %>
Refrain<br />
Je veux t'aimer sans cesse de plus en plus.<br />
Protège ma promesse Seigneur Jésus !<br />
<br />
<div class="row">
  <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
    1/ Devant tous je m'engage<br />
    Sur mon honneur<br />
    Et je te fais hommage<br />
    De moi, Seigneur !<br />
    <br />
  </div>
  <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
    2/ Je jure de te suivre<br />
    En fier chrétien<br />
    Et tout entier je livre<br />
    Mon coeur au Tien.<br />
    <br />
  </div>
  <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
    3/ Je jure d'être fière<br />
    De notre foi <br />
    De vivre à ta lumière<br />
    Tout près de Toi.<br />
    <br />
  </div>
  <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
    4/ Fidèle à ma patrie<br />
    Je le serai<br />
    Tous les jours de ma vie<br />
    Je servirai.<br />
    <br />
  </div>
  <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
    5/ Je suis de tes apôtres<br />
    Et chaque jour<br />
    Je veux aider les autres<br />
    Pour ton amour.<br />
    <br />
  </div>
  <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
    6/ Ta règle a sur nous-mêmes<br />
    Un droit sacré<br />
    Je suis faible, tu m'aimes<br />
    Je maintiendrai !<br />
    <br />
  </div>
</div>
</p>
<% when 10 %>
<p>
Mendiez, mendiez, l’humilité du cœur,<br />
mendiez, mendiez, la grâce de la prière,<br />
Soyez fils et filles de la lumière.<br />
</p>
<% when 11 %>
<p>
Refrain<br />
Ne crains pas je suis ton Dieu. C'est moi qui t'ai choisi appelé par ton nom,<br />
tu as du prix à mes yeux car je t'aime, ne crains pas car je suis avec toi.<br />
<br />
Toi mon serviteur je te soutiendrai, toi mon élu que préféré mon âme,<br />
je mettrai en toi mon Esprit je te comblerai de mon Esprit.<br />
<br />
Le seigneur m'a appelé dès le sein de ma mère, il a prononcé mon nom.<br />
C'est lui qui m'a formé pour être mon serviteur le témoin de sa gloire.
</p>
<% when 12 %>
<% when 13 %>
<% when 14 %>
<% when 15 %>
<p>
<div class="row">
  <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
    R/ Tu es là présent, livré pour nous.<br />
    Toi le tout-petit, le serviteur.<br />
    Toi, le Tout-Puissant, humblement tu t´abaisses.<br />
    Tu fais ta demeure en nous Seigneur.<br />
    <br />
  </div>
  <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
    1/ Le pain que nous mangeons, le vin que nous buvons,<br />
    C´est ton corps et ton sang,<br />
    Tu nous livres ta vie, tu nous ouvres ton cœur,<br />
    Tu fais ta demeure en nous Seigneur.<br />
    <br />
  </div>
  <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
    2/ Par le don de ta vie, tu désires aujourd´hui<br />
    Reposer en nos cœurs,<br />
    Brûlé de charité, assoiffé d´être aimé,<br />
    Tu fais ta demeure en nous Seigneur.<br />
    <br />
  </div>
  <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
    3/ Unis à ton Amour, tu nous veux pour toujours<br />
    Ostensoirs du Sauveur,<br />
    En notre humanité, tu rejoins l´égaré,<br />
    Tu fais ta demeure en nous Seigneur.<br />
    <br />
  </div>
</div>
</p>
<% when 16 %>
<p>
Refrain<br />
Humblement, dans le silence de mon cœur,<br />
je me donne à toi, mon Seigneur.<br />
<br />
1/ Par ton amour, fais-moi demeurer humble et petit devant toi.<br />
<br />
2/ Entre tes mains, je remets ma vie, ma volonté, tout mon être.<br />
<br />
3/ Enseigne-moi ta sagesse, Ô Dieu, viens habiter mon silence.<br />
<br />
4/ Je porte en moi ce besoin d'amour, de me donner, de me livrer, sans retour.<br />
<br />
5/ Vierge Marie, garde mon chemin dans l'abandon, la confiance de l'amour.<br />
</p>
<% when 17 %>
<p>
<div class="row">
  <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
    1/ Si le vent des tentations s'élève,<br />
    Si tu heurtes le rocher des épreuves.<br />
    Si les flots de l'ambition t'entraînent,<br />
    Si l'orage des passions se déchaîne :<br />
    <br />
  </div>
  <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
    R/ Regarde l’étoile, invoque Marie,<br />
    Si tu la suis, tu ne crains rien !<br />
    Regarde l’étoile, invoque Marie,<br />
    Elle te conduit sur le chemin !<br />
    <br />
  </div>
  <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
    2/ Dans l'angoisse et les périls, le doute,<br />
    Quand la nuit du désespoir te recouvre.<br />
    Si devant la gravité de tes fautes<br />
    La pensée du jugement te tourmente :<br />
    <br />
  </div>
  <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
    3/ Si ton âme est envahie de colère,<br />
    Jalousie et trahison te submergent.<br />
    Si ton coeur est englouti dans le gouffre,<br />
    Emporté par les courants de tristesse :<br />
    <br />
  </div>
  <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
    4/ Elle se lève sur la mer, elle éclaire,<br />
    Son éclat et ses rayons illuminent.<br />
    Sa lumière resplendit sur la terre,<br />
    Dans les cieux et jusqu'au fond des abîmes.<br />
    <br />
  </div>
  <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
    A/ Si tu la suis, tu ne dévies pas,<br />
    Si tu la pries, tu ne faiblis pas.<br />
    Tu ne crains rien, elle est avec toi,<br />
    Et jusqu’au port, elle te guidera.<br />
    <br />
  </div>
</div>
</p>
<% when 18 %>
<p>
Refrain<br />
Jubilez ! Criez de joie ! Acclamez le Dieu trois fois Saint !<br />
Venez le prier dans la paix ; témoigner de son amour<br />
Jubilez ! Criez de joie ! pour Dieu notre Dieu.<br />
<br />
<div class="row">
  <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
    1/ Louez le Dieu de lumière<br />
    Il nous arrache aux ténèbres<br />
    Devenez en sa clarté<br />
    Des enfants de sa lumière.<br />
    <br />
  </div>
  <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
    2/ Ouvrez vous, ouvrez vos cœurs<br />
    Au Dieu de miséricorde<br />
    Laissez-vous réconcilier<br />
    Laissez-vous transfigurer<br />
    <br />
  </div>
  <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
    3/ Notre Dieu est tout amour<br />
    Toute paix toute tendresse<br />
    Demeurez en son amour<br />
    Il vous comblera de Lui<br />
    <br />
  </div>
  <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
    4/ À l’ouvrage de sa grâce<br />
    Offrez toute votre vie<br />
    Il pourra vous transformer<br />
    Lui, le Dieu qui sanctifie.<br />
    <br />
  </div>
  <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
    5/ Louange au Père et au Fils<br />
    Louange à l’Esprit de gloire<br />
    Bienheureuse Trinité :<br />
    Notre joie et notre vie !<br />
    <br />
  </div>
</div>
</p>
<% end %>

app/views/songs/index.html.erb
<h1>Chants de la messe</h1>
<p>Je répète pour la chorale, je <%= link_to "télécharge toutes les partitions", songs_path("zip"), target: "_blank" %></p>

<div class="row main_grey">
	<div class="col-xs-12 col-sm-5 col-md-4 col-lg-4">
		<div id="jquery_jplayer_1" class="jp-jplayer">
		# <audio id="jp_audio_0" preload="metadata" src="http://127.0.0.1:3000/audios/sarabande.ogg"></audio>
		</div>
		<div id="jp_container_1" class="jp-audio image-responsive">
			<div class="jp-type-playlist">
				<div class="jp-gui jp-interface">
					<ul class="jp-controls">
						<li><a href="javascript:;" class="jp-previous" tabindex="1">previous</a></li>
						<li><a href="javascript:;" class="jp-play" tabindex="1">play</a></li>
						<li><a href="javascript:;" class="jp-pause" tabindex="1">pause</a></li>
						<li><a href="javascript:;" class="jp-next" tabindex="1">next</a></li>
						<li><a href="javascript:;" class="jp-stop" tabindex="1">stop</a></li>
<!-- 						<li><a href="javascript:;" class="jp-mute" tabindex="1" title="mute">mute</a></li>
						<li><a href="javascript:;" class="jp-unmute" tabindex="1" title="unmute">unmute</a></li>
						<li><a href="javascript:;" class="jp-volume-max" tabindex="1" title="max volume">max volume</a></li> -->
					</ul>
					<div class="jp-progress">
						<div class="jp-seek-bar">
							<div class="jp-play-bar"></div>
						</div>
					</div>
<!-- 					<div class="jp-volume-bar">
						<div class="jp-volume-bar-value"></div>
					</div> -->
					<div class="jp-time-holder">
						<div class="jp-current-time"></div>
						<div class="jp-duration"></div>
					</div>
<!-- 					<ul class="jp-toggles">
						<li><a href="javascript:;" class="jp-repeat" tabindex="1" title="repeat">repeat</a></li>
						<li><a href="javascript:;" class="jp-repeat-off" tabindex="1" title="repeat off">repeat off</a></li>
					</ul> -->
				</div>
				<div class="jp-playlist">
					<ul>
						<li></li>
					</ul>
				</div>
				<div class="jp-no-solution">
					<span>Update Required</span>
					To play the media you will need to either update your browser to a recent version or update your <a href="http://get.adobe.com/flashplayer/" target="_blank">Flash plugin</a>.
				</div>
			</div>
		</div>
	</div>
	<div class="col-xs-12 col-sm-7 col-md-8 col-lg-8">
		<% Song.all.each do |song| %>
		<div class="words" id="<%= song.name %>">
			<%= render(partial: "words", locals: {song: song}) %>
		</div>
		<% end %>
	</div>
</div>

<% content_for :script do %>
<script type="text/javascript">
	$(document).ready(function(){
		new jPlayerPlaylist({
			jPlayer: "#jquery_jplayer_1",
			cssSelectorAncestor: "#jp_container_1"
		}, [
			{
				<%= Song.all.collect{|song| %Q{title:\"#{song.title} - #{song.type}\", mp3:\"#{audio_path(song.name+".mp3")}\", oga:\"#{audio_path(song.name+".ogg")}\"} }.join("\n\t\t}, {\n\t\t\t").html_safe %>
			}
		], {
			swfPath: "../js",
			supplied: "oga, mp3",
			wmode: "window",
			smoothPlayBar: true,
			keyEnabled: true
		});
		$("div.words").hide();
		$("#jquery_jplayer_1").bind($.jPlayer.event.play, function(){
			$name = $("audio").attr('src').split(/\//).pop().split(/\./).shift();
			$("div.words").hide();
			$("div.words#"+$name).show();
		});
	});
</script>
<% end %>

app/views/songs/show.html.erb
<%= render(partial: "song", locals: {song: @song}) %>
<%= render(partial: "words", locals: {song: @song}) %>