config/routes.rb
Wedding::Application.routes.draw do
  
  get "users/new/:object" => "users#new", as: :new_user
  get "users/:id/edit/:object" => "users#edit", as: :edit_user 
  resources :users, except: [:new, :edit] do
    collection do
      get :authentification
      post :authenticate
    end
  end

  resources :songs

  resources :welcomes, only: [:index]
  
  namespace :admin do
    resources :users, only: [] do
      collection do
        get :responses
        get :addresses
        get :messages
      end
    end
    root 'users#responses'
  end

  root 'welcomes#index'

end

app/models/user.rb
# coding: utf-8
# 
# == Schema Information
#
# Table name: users
#
#  id                 :integer          not null, primary key
#  firstname          :string(255)
#  lastname           :string(255)
#  email              :string(255)
#  login              :string(255)
#  salt               :string(255)
#  encrypted_password :string(255)
#  partner_id         :integer
#  street             :string(255)
#  address_add        :string(255)
#  town               :string(255)
#  zip_code           :string(255)
#  message_address    :text
#  created_at         :datetime
#  updated_at         :datetime
#  presence           :string(255)
#  message_response   :string(255)
#  phone              :string(255)
#

require 'bcrypt'
require 'yaml'
require 'csv'

class String
  def without_accent
    gsub(/[ÀÁÂÃÄáàâäã]/, "a").gsub(/[Çç]/, "c").gsub(/[ÈÉÊËẼéèêëẽ]/, "e").gsub(/[ÌÍÎÏĨîïíĩì]/, "i").gsub(/[ÒÓÔÕÖôöóòõ]/, "i").gsub(/[ÙÚÛÜŨùúûüũ]/, "i").titleize
  end
end

class User < ActiveRecord::Base
	before_validation :cypher_password, if: :password
	before_validation :set_login
  before_save :set_response
	after_save :save_partner

	validates_uniqueness_of :login
	validates_presence_of :login

	def password=(password); @password = password; end
	def password; @password; end

	def name; "#{self[:firstname]} #{self[:lastname]}"; end

	def wedding=(value); response[:wedding] = value; end
	def cocktail=(value); response[:cocktail] = value; end
	def dinner=(value); response[:dinner] = value; end
	def party=(value); response[:party] = value; end
	def wedding; response[:wedding]; end
	def cocktail; response[:cocktail]; end
	def dinner; response[:dinner]; end
	def party; response[:party]; end
	def set_response; self.presence = self.response.to_yaml; end
	def response; @response ||= (self.presence ? YAML.load(presence) : {}); end
  def response?; response.present?; end
  def comes?; presence =~ /1/; end

	def partner; @partner ||= User.new; end
	def partner=(partner); @partner = partner; end
	def save_partner
		if partner[:firstname].present?
			self.class.where(login: self.class.login( partner)).first_or_create!.update_attributes!(partner)
		end
		true
  rescue
    true
	end

	def set_login;	self[:login] ||= User.login(self);	end
	def self.login(user_hash); puts user_hash[:firstname]; "#{user_hash[:firstname]}#{user_hash[:lastname]}".without_accent.gsub(/\s+/, "");		end

	def self.create_admin_user(password)
		User.where(firstname: "admin", lastname: "admin", login: "admin").first_or_create!.update_attributes!(password: password)
	end
	def self.admin_user
    	find_by!(firstname: "admin", lastname: "admin", login: "admin")
	end
	def self.create_default_user(password)
		User.where(firstname: "default", lastname: "user", login: "default user").first_or_create!.update_attributes!(password: password)
	end
	def self.default_user
    	find_by!(firstname: "default", lastname: "user", login: "default user")
	end
	  
	def self.name_without_accent(hash)
		{firstname: hash[:firstname], lastname: hash[:lastname].without_accent}
	end

	def cypher_password
		self[:salt] = BCrypt::Engine.generate_salt
		self[:encrypted_password] = BCrypt::Engine.hash_secret(@password, self[:salt])
	end

	def self.check_admin_password(password)
		BCrypt::Engine.hash_secret(password, admin_user[:salt]) == admin_user[:encrypted_password]
	end
	def self.check_default_password(password)
		BCrypt::Engine.hash_secret(password, default_user[:salt]) == default_user[:encrypted_password]
	end
  
  
  ##### EXPORT CSV
  
  ADDRESS_HEADER = ["Nom", "Prénom", "Rue", "Complément", "Ville", "Code postal", "Adresse internet", "Téléphone", "Nom", "Prénom", "Message"]
  RESPONSE_HEADER = ["Nom", "Prénom", "Cérémonie", "Cocktail", "Dinner", "Soirée", "Nom", "Prénom", "Cérémonie", "Cocktail", "Dinner", "Soirée", "Message"]
  
  def self.users_with_address; User.where("town IS NOT NULL").all; end
  def self.addresses
    CSV.generate( col_sep: ";") do |csv|
      csv << ADDRESS_HEADER
      User.users_with_address.each{ |user| csv << [user[:lastname], user[:firstname], user[:street], user[:address_add], user[:town], user[:zip_code], user[:email], user[:phone], user.partner.try(:lastname), user.partner.try(:firstname), user[:message_address],]} #
    end
  end
  def self.users_with_response; User.where("presence != '--- {}\n'").all; end
  def self.responses
    CSV.generate( col_sep: ";") do |csv|
      csv << RESPONSE_HEADER
      User.users_with_response.each{ |user| csv << [user[:lastname], user[:firstname], user.wedding, user.cocktail, user.dinner, user.party, user.partner.try(:lastname), user.partner.try(:firstname), user.partner.try(:wedding), user.partner.try(:cocktail), user.partner.try(:dinner), user.partner.try(:party), user[:message_response],]} #
    end
  end
  
end

app/controllers/admin/users_controller.rb
# coding: utf-8
# 

class Admin::UsersController < ApplicationController
  
  before_action :authenticated_filter
  
  def addresses
    do_and_respond(:addresses) do
      if csv_request?
        @csv = User.addresses
        @filename = "adresses.csv"
      else
        @users = User.users_with_address
      end
    end
  end
  def responses
    do_and_respond(:responses) do
      if csv_request?
        @csv = User.responses
        @filename = "responses.csv"
      else
        @users = User.users_with_response
      end
    end
  end
  def messages
    do_and_respond(:messages) do
      @users = User.all
    end
  end

private
  def user_params
    params.require(:user).except!(:login, :password, :encrypted_password).permit!
  end
end

app/controllers/users_controller.rb
# coding: utf-8
# 

class UsersController < ApplicationController

  def index
    do_and_respond(:index) do
    end
  end

  def show
    do_and_respond(:show) do
    end
  end

  def new
    puts ["new", params, @current_user.try(:name)]
    return edit if @current_user
    do_and_respond(:new) do
      @current_user = User.new
      @object = params[:object]
    end
  end
  
  def edit
    puts ["edit", params, @current_user.try(:name)]
    do_and_respond(:edit, :show) do
      @object = params[:object]
    end
  end
  
  def create
    puts ["create", params, @current_user.try(:name)]
    update
  end
  
  def update
    puts ["update", params, @current_user.try(:name)]
    do_and_respond(:redirect_to_welcomes_path) do
      @current_user = User.where(login: User.login(user_params)).first_or_create!
      @current_user.update_attributes!(user_params)
    end
  end
  
  def authentification
    do_and_respond(:authentification, :index) do
    end
  end
  
  def authenticate
    puts params[:password]
    do_and_respond(:redirect_to_responses_admin_users_path, :authentification) do
      @authenticated = "authentification de premier niveau" if User.check_admin_password(params[:password])
      raise "Utilisateur non authentifié" if @authenticated != "authentification de premier niveau"
    end
  end

private
  def user_params
    params.require(:user).except!(:login, :password, :encrypted_password).permit!
  end
end

app/views/admin/users/addresses.html.erb
<h2 class="text-center">Administration des invités</h2>
<div class="row main_grey">
  <div class="col-xs-12 col-sm-10 col-md-8 col-lg-6 col-sm-offset-1 col-md-offset-2 col-lg-offset-3">
    <%= link_to "Réponses", responses_admin_users_path %>
    <%= link_to "Messages", messages_admin_users_path %>
    <table class="table table-condensed">
      <thead>
        <tr>
          <th>Nom</th>
          <th>Prénom</th>
          <th>Rue</th>
          <th>Complément</th>
          <th>Code postal</th>
          <th>Ville</th>
          <th>Message</th>
        </tr>
      </thead>
      <tbody>
        <% @users.each do |user| %>
        <tr class="<%= user.response? ? user.comes? ? "success" : "error" : nil %>">
          <td><%= user[:lastname]%></td>
          <td><%= user[:firstname]%></td>
          <td><%= user[:street]%></td>
          <td><%= user[:address_add]%></td>
          <td><%= user[:zip_code]%></td>
          <td><%= user[:town]%></td>
          <td><%= user[:message_address]%></td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/admin/users/index.html.erb
<h2 class="text-center">Administration des invités</h2>
<div class="row main_grey">
  <div class="col-xs-12 col-sm-10 col-md-8 col-lg-6 col-sm-offset-1 col-md-offset-2 col-lg-offset-3">
    <table class="table table-condensed">
      <thead>
        <tr>
          <th>Nom</th>
          <th>Prénom</th>
          <th>Rue</th>
          <th>Complément</th>
          <th>Code postal</th>
          <th>Ville</th>
        </tr>
      </thead>
      <tbody>
        <% User.where("town IS NOT NULL").all.each do |user| %>
        <tr class="<%= user.response? ? user.comes? ? "success" : "error" : nil %>">
          <td><%= user[:lastname]%></td>
          <td><%= user[:firstname]%></td>
          <td><%= user[:street]%></td>
          <td><%= user[:address_add]%></td>
          <td><%= user[:zip_code]%></td>
          <td><%= user[:town]%></td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/admin/users/messages.html.erb
<h2 class="text-center">Administration des invités</h2>
<div class="row main_grey">
  <div class="col-xs-12 col-sm-10 col-md-8 col-lg-6 col-sm-offset-1 col-md-offset-2 col-lg-offset-3">
    <%= link_to "Réponses", responses_admin_users_path %>
    <%= link_to "Adresses", addresses_admin_users_path %>
    <table class="table table-condensed">
      <thead>
        <tr>
          <th>Messages</th>
        </tr>
      </thead>
      <tbody>
        <% @users.each do |user| %>
          <% if user[:message_address].present? || user[:message_response].present? %>
          <tr class="<%= user.response? ? user.comes? ? "success" : "error" : nil %>">
            <td><%= "#{user[:firstname]} #{user[:lastname]}" %></td>
          </tr>
          <% end %>
          <% if user[:message_address].present? %>
          <tr class="<%= user.response? ? user.comes? ? "success" : "error" : nil %>">
            <td><%= user[:message_address] %></td>
          </tr>
          <% end %>
          <% if user[:message_response].present? %>
          <tr class="<%= user.response? ? user.comes? ? "success" : "error" : nil %>">
            <td><%= user[:message_response] %></td>
          </tr>
          <% end %>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/admin/users/responses.html.erb
<h2 class="text-center">Administration des invités</h2>
<div class="row main_grey">
  <div class="col-xs-12 col-sm-10 col-md-8 col-lg-6 col-sm-offset-1 col-md-offset-2 col-lg-offset-3">
    <%= link_to "Adresses", addresses_admin_users_path %>
    <%= link_to "Messages", messages_admin_users_path %>
    <table class="table table-condensed">
      <thead>
        <tr>
          <th>Nom</th>
          <th>Prénom</th>
          <th>Cérémonie</th>
          <th>Cocktail</th>
          <th>Diner</th>
          <th>Soirée</th>
          <th>Message</th>
        </tr>
      </thead>
      <tbody>
        <% @users.each do |user| %>
        <tr class="<%= user.response? ? user.comes? ? "success" : "error" : nil %>">
          <td><%= user[:lastname] %></td>
          <td><%= user[:firstname] %></td>
          <td><%= user.wedding == "1" ? "1" : nil %></td>
          <td><%= user.cocktail == "1" ? "1" : nil %></td>
          <td><%= user.dinner == "1" ? "1" : nil %></td>
          <td><%= user.party == "1" ? "1" : nil %></td>
          <td><%= user[:message_response] %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>