config/routes.rb
Wedding::Application.routes.draw do
  
  get "users/new/:object" => "users#new", as: :new_user
  get "users/:id/edit/:object" => "users#edit", as: :edit_user 
  resources :users, except: [:new, :edit] do
    collection do
      get :authentification
      post :authenticate
    end
  end

  resources :songs

  resources :welcomes, only: [:index]
  
  namespace :admin do
    resources :users, only: [] do
      collection do
        get :responses
        get :addresses
        get :messages
      end
    end
    root 'users#responses'
  end

  root 'welcomes#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mariage Malou et Manu</title>
  <%= favicon_link_tag %>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= csrf_meta_tags %>
</head>
<body class="">
  <nav class="navbar navbar-default navbar-static-top" role="navigation">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "Accueil", welcomes_path, class: "navbar-brand" %>
      </div>
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li><%= link_to "Chants", songs_path %></li>
          <li><%= link_to "Réponse", new_user_path(:response) %></li>
          <li><%= link_to "Trajet", welcomes_path %></li>
          <li><%= link_to "Soirée", welcomes_path %></li>
          <li><%= link_to "Liste", "http://www.millemercismariage.com/maloumanu/liste.html", target: "_blank" %></li>
          <li><%= link_to "Photos", welcomes_path %></li>
          <% if authenticated? %>
          <li><%= link_to( "Adresses", addresses_admin_users_path(:csv)) %></li>
          <li><%= link_to( "Réponses", responses_admin_users_path(:csv)) %></li>
          <% end %>
        </ul>
        <p class="navbar-text navbar-right" id="countdown"></p>
      </div>
    </div>
  </nav>
  <div class="container-fluid">
    <%= yield %>
  </div>
  
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= yield :script %>
  <script type="text/javascript">
    $(document).ready(function(){
      // set the date we're counting down to
      var target_date = new Date(2014,9,25,14,0,0).getTime();
      // variables for time units
      var days, hours, minutes, seconds;
      // get tag element
      var countdown = document.getElementById('countdown');
      // update the tag with id "countdown" every 1 second
      setInterval(function () {
        // find the amount of "seconds" between now and target
        var current_date = new Date().getTime();
        var seconds_left = (target_date - current_date) / 1000;
        // do some time calculations
        days = parseInt(seconds_left / 86400);
        seconds_left = seconds_left % 86400;
         
        hours = parseInt(seconds_left / 3600);
        seconds_left = seconds_left % 3600;
         
        minutes = parseInt(seconds_left / 60);
        seconds = parseInt(seconds_left % 60);
         
        // format countdown string + set tag value
        countdown.innerHTML = days +  ' jours ' + hours + ':' + minutes + ':' + seconds;
      },
      1000);
    });
  </script>
  <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyApC8568UgUkwrt7DMfNpq0KtxKOwhiTbE&sensor=false&language=fr">
  </script>
  <script type="text/javascript">
    function initialize() {
      var egliseLatlng = new google.maps.LatLng(48.804277,2.146196)
      var mapOptions = {
        center: egliseLatlng,
        zoom: 13
      };
      var map_eglise = new google.maps.Map(document.getElementById("map-eglise"), mapOptions);
      var marker = new google.maps.Marker({
        position: egliseLatlng,
        map: map_eglise,
        title: "Église Saint-Symphorien\n2 Place Saint-Symphorien, 78000 Versailles"
      });
      var chateauLatlng = new google.maps.LatLng(48.317922,1.990113)
      var mapOptions = {
        center: chateauLatlng,
        zoom: 10
      };
      var map_chateau = new google.maps.Map(document.getElementById("map-chateau"), mapOptions);
      var marker = new google.maps.Marker({
        position: chateauLatlng,
        map: map_chateau,
        title: "Chateau de Dommerville\n55 Rue de la Plaine, 91670 Angerville"
      });
    }
    google.maps.event.addDomListener(window, 'click', initialize);
    $(document).ready(function(){initialize();});
  </script>
</body>
</html>